In [2]:
list(range(0, 5600, 1000))

[0, 1000, 2000, 3000, 4000, 5000]

In [1]:
for r, s in zip('abc', (5, 6, 9)):
    print(r, s)

a 5
b 6
c 9


In [1]:
import numpy as np

In [3]:
np.array((1, 2, 3))

array([1, 2, 3])

In [4]:
(1,2,3)

(1, 2, 3)

In [6]:
type(np.array((1, 2, 3)))

numpy.ndarray

In [7]:
type((1, 2, 3))

tuple

In [2]:
a = np.array((1, 2, 3))
b = np.array((77, 88))
np.concatenate([a, b])

array([ 1,  2,  3, 77, 88])

In [7]:
a = np.array((1, 2, 3))
b = np.array((77, 88))
np.append(a, b)

array([ 1,  2,  3, 77, 88])

In [18]:
a[:2]

array([1, 2])

In [19]:
a[2:]

array([3])

In [14]:
np.empty(2, dtype=np.float)

array([6.6995302e-321, 9.7713459e-153])